version: '3'

services:
  ehairdressersalonfare.api:
    image: ehairdressersalonfareapi:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_ehairdressersalonfare.api$
    volumes:
      - C:\Users\ZZO5\Desktop\DesktopMobileApp-for-hairdresser-salon-Fare\eHairdresserSalonFare\eHairdresserSalonFare.Api:/app
      - C:\Users\ZZO5\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_ehairdressersalonfare.api$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_ehairdressersalonfare.api$ \"bin/Debug/netcoreapp2.2/eHairdresserSalonFare.Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
